### ISSUE TITLE
Can't seem to create a new \Smartsheet\Client

### ISSUE THREAD

**Issue by erfanimani** [silinternational/smartsheet-php-client#2]
Recoverable Error: Argument 2 passed to `GuzzleHttp\Command\Guzzle\GuzzleClient::getCommand()` must be of the type array, string given, called in `/vendor/guzzlehttp/command/src/AbstractClient.php` on line 68 and defined  in `/vendor/guzzlehttp/guzzle-services/src/GuzzleClient.php` on line 59

```
#0 vendor/guzzlehttp/guzzle-services/src/GuzzleClient.php(59): mageCoreErrorHandler(4096, 'Argument 2 pass...', '/srv/www/...', 59, Array)
#1 vendor/guzzlehttp/command/src/AbstractClient.php(68): GuzzleHttp\Command\Guzzle\GuzzleClient->getCommand('setConfig', 'defaults/ApiVer...')
#2 vendor/silinternational/smartsheet-php-client/src/Client.php(46): GuzzleHttp\Command\AbstractClient->__call('setConfig', Array)
#3 vendor/silinternational/smartsheet-php-client/src/Client.php(46): Smartsheet\Client->setConfig('defaults/ApiVer...', '1.1')
#4 app/code/core/Mage/Contacts/controllers/IndexController.php(56): Smartsheet\Client->__construct(Array)
```

Seems like an easy fix. Will investigate soonish...

**Comment by fillup** [comment]
@erfanimani can you provide your code that triggered the error so I can see how to duplicate?

**Comment by erfanimani** [comment]
Hi @fillup,

The code that I'm running is:

```
new \Smartsheet\Client([
    'access_token' => $token,
]);
```

The issue seems to happen in `\Smartsheet\Client::__construct` in the following statement:

```
   // Ensure that ApiVersion is set.
    $this->setConfig(
        'defaults/ApiVersion',
        $this->getDescription()->getApiVersion()
    );
```

Maybe it's because Guzzle changed its API or something, the version this package depends on is quite broad (`*`). 

I'll investigate further when I get the chance.

**Comment by fillup** [comment]
@erfanimani I bet you are right about Guzzle api changing, I didnt realize I had such a broad requirement there. I'll see if I can get that fixed pretty quick.

**Comment by fillup** [comment]
@erfanimani I am not able to duplicate this. I just did a composer update as well to ensure I had all the latest versions and it is still working for me. I updated the unit tests for the count statements to account for statusCode being part of the array and not just the users, but no errors with with construction or anything.

**Comment by erfanimani** [comment]
Hmm interesting @fillup, do you have PHP errors/warnings on? I actually don't think the `setConfig` method exists any more:

```
## 0.8.0 - 2015-02-02

* Removed `setConfig` from `ServiceClientInterface`.
* Added `initTransaction` to `ServiceClientInterface`.
```

Source: https://github.com/guzzle/command/blob/master/CHANGELOG.md

Probably the reason why it's not giving a fatal error is because the `setConfig` call is being intercepted by Guzzle/Command's `__call` method which tries to execute the `getCommand` method (which in your case is bailing with an ignored recoverable error, instead of a fatal error `method does not exist`.)

**Comment by fillup** [comment]
@erfanimani, perhaps we are running different versions of the dependencies. Have you run a `composer update` recently? Checking my `composer.lock` file I see I'm using:
- guzzlehttp/command 0.7.1
- guzzlehttp/guzzle 5.3.0
- guzzlehttp/guzzle-services 0.5.0
- guzzlehttp/log-subscriber 1.0.1
- guzzlehttp/retry-subscriber 2.0.2
- guzzlehttp/ringphp 1.1.0
- guzzlehttp/streams 3.0.0
- psr/log 1.0.0
- react/promise v2.2.1

When I run unit tests I get:

```
$ ./vendor/bin/phpunit tests/
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

......

Time: 495 ms, Memory: 7.00Mb

OK (6 tests, 8 assertions)
```

Are you able to run unit tests?

**Comment by erfanimani** [comment]
Ah interesting... doing `composer show -i` tells me I'm pulling in the `dev-master` version for almost ever guzzle package except for `guzzlehttp/guzzle`. It makes sense if you look at the composer.json: https://github.com/silinternational/smartsheet-php-client/blob/master/composer.json . I'll lock it to the versions you've specified - thanks for that. Oddly enough the tests were running fine.
