### ISSUE TITLE
Unable to configure Update call

### ISSUE THREAD

**Issue by michielpw75** [silinternational/smartsheet-php-client#6]
I try to do an update call using this library, added some configuration for this to the smartsheet-api.php file:
'UpdateCell' => [
            'httpMethod' => 'PUT',
            'uri' => '/{ApiVersion}/sheets/{sheetId}/rows',
            'responseModel' => 'Result',
            'parameters' => [
                'ApiVersion' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ],
				'sheetId' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ],
				'id' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'json',
                ],
				'cells' => [
					'required' => true,
					'type' => 'array',
					'location' => 'json'
					,
					'columnId' => [
						'required' => true,
						'type'     => 'string',
						'location' => 'json',
					],
					'value' => [
						'required' => true,
						'type'     => 'string',
						'location' => 'json',
					]
				]
                
            ]
        ]

IN debugging I see a correct call:
HTTP/1.1 Host: api.smartsheet.com Authorization: Bearer syv26hsi79lbjgmjiidehvi110 Content-Type: application/json {"id":"12345617890","cells":{"columnId":12345617890,"value":"2019-01-03"}}
(see documentation: https://smartsheet-platform.github.io/api-docs/#update-rows)

But the response is:
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error response [url] https://api.smartsheet.com/2.0/sheets/1234567890/rows [status code] 400 [reason phrase] Bad Request in E:\wwwroot\Finance.pw.com\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:89 Stack trace: #0 E:\wwwroot\Finance.pw.com\vendor\guzzlehttp\guzzle\src\Subscriber\HttpError.php(32): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response)) #1 E:\wwwroot\Finance.pw.com\vendor\guzzlehttp\guzzle\src\Event\Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete') #2 E:\wwwroot\Finance.pw.com\vendor\guzzlehttp\guzzle\src\RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent)) #3 E:\wwwroot\Finance.pw.com\vendor\guzzlehttp\guzzle\src\RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction)) #4 E:\wwwroot\Finance.pw.com\vendor\react\promise in E:\wwwroot\Finance.pw.com\vendor\guzzlehttp\command\src\AbstractClient.php on line 171

Can you please help! Thanks a lot.

I also added the following call to the file and they are working great!

		'ListSheets' => [
            'httpMethod' => 'GET',
            'uri' => '/{ApiVersion}/sheets',
            'responseModel' => 'Sheet',
            'parameters' => [
                'ApiVersion' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ],
                'email' => [
                    'required' => false,
                    'type' => 'string',
                    'location' => 'query',
                ],
            ]
        ],
		'Sheet' => [
            'httpMethod' => 'GET',
            'uri' => '/{ApiVersion}/sheets/{sheetId}?include=format',
            'responseModel' => 'Sheet',
            'parameters' => [
                'ApiVersion' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ],
                'sheetId' => [
                    'required' => true,
                    'type' => 'string',
                    'location' => 'uri',
                ],
            ]
        ],
		'ListOrgSheets' => [
            'httpMethod' => 'GET',
            'uri' => '/{ApiVersion}/users/sheets?includeAll=true',
            'responseModel' => 'Sheet',
            'parameters' => [
                'ApiVersion' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ],
                'email' => [
                    'required' => false,
                    'type' => 'string',
                    'location' => 'query',
                ],
            ]
        ]
		,
		'ListSheetShares' => [
            'httpMethod' => 'GET',
            'uri' => '/{ApiVersion}/sheets/{sheetId}/shares?includeAll=true',
            'responseModel' => 'Sheet',
            'parameters' => [
                'ApiVersion' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ],
                'sheetId' => [
                    'required' => true,
                    'type' => 'string',
                    'location' => 'uri',
                ],
                'include' => [
                    'required' => false,
                    'type' => 'string',
                    'location' => 'query',
                ]
            ]
        ],
		'DeleteSheetShares' => [
            'httpMethod' => 'DELETE',
            'uri' => '/{ApiVersion}/sheets/{sheetId}/shares/{shareId}',
            'responseModel' => 'Sheet',
            'parameters' => [
                'ApiVersion' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ],
                'sheetId' => [
                    'required' => true,
                    'type' => 'string',
                    'location' => 'uri',
                ],
				'shareId' => [
                    'required' => true,
                    'type' => 'string',
                    'location' => 'uri',
                ]
            ]
        ],
		'ListWorkspaces' => [
            'httpMethod' => 'GET',
            'uri' => '/{ApiVersion}/workspaces?includeAll=true',
            'responseModel' => 'Result',
            'parameters' => [
                'ApiVersion' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ]
            ]
        ],
		'ListWorkspaceShares' => [
            'httpMethod' => 'GET',
            'uri' => '/{ApiVersion}/workspaces/{workspaceId}/shares?includeAll=true',
            'responseModel' => 'Result',
            'parameters' => [
                'ApiVersion' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ],
                'workspaceId' => [
                    'required' => true,
                    'type' => 'string',
                    'location' => 'uri',
                ]
            ]
        ],
		'Workspace' => [
            'httpMethod' => 'GET',
            'uri' => '/{ApiVersion}/workspaces/{workspaceId}?includeAll=true',
            'responseModel' => 'Result',
            'parameters' => [
                'ApiVersion' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ],
                'workspaceId' => [
                    'required' => true,
                    'type' => 'string',
                    'location' => 'uri',
                ]
            ]
        ],
		'Folder' => [
            'httpMethod' => 'GET',
            'uri' => '/{ApiVersion}/folders/{folderId}?includeAll=true',
            'responseModel' => 'Result',
            'parameters' => [
                'ApiVersion' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ],
                'folderId' => [
                    'required' => true,
                    'type' => 'string',
                    'location' => 'uri',
                ]
            ]
        ],
		'Contacts' => [
            'httpMethod' => 'GET',
            'uri' => '/{ApiVersion}/contacts',
            'responseModel' => 'Result',
            'parameters' => [
                'ApiVersion' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ]
            ]
        ],
		'Users' => [
            'httpMethod' => 'GET',
            'uri' => '/{ApiVersion}/users',
            'responseModel' => 'Result',
            'parameters' => [
                'ApiVersion' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ]
            ]
        ],
        'CreateWebhook' => [
            'httpMethod' => 'POST',
            'uri' => '/{ApiVersion}/webhooks',
            'responseModel' => 'Result',
            'parameters' => [
                'ApiVersion' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ],
                'name' => [
                    'required' => true,
                    'type' => 'string',
                    'location' => 'json'
                ],
                'callbackUrl' => [
                    'required' => true,
                    'type' => 'string',
                    'location' => 'json'
                ],
                'scope' => [
                    'required' => true,
                    'type' => 'string',
                    'location' => 'json',
                ],
                'events' => [
                    'required' => true,
                    'type' => 'array',
                    'location' => 'json',
                ],
                'scopeObjectId' => [
                    'required' => true,
                    'type' => 'number',
                    'location' => 'json'
                ],
                'version' => [
                    'required' => true,
                    'type' => 'number',
                    'location' => 'json',
                ]
            ]
        ],
        'UpdateWebhook' => [
            'httpMethod' => 'PUT',
            'uri' => '/{ApiVersion}/webhooks/{webhookId}',
            'responseModel' => 'Result',
            'parameters' => [
                'ApiVersion' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ],
				'webhookId' => [
                    'required' => true,
                    'type'     => 'string',
                    'location' => 'uri',
                ],
                'name' => [
                    'required' => false,
                    'type' => 'string',
                    'location' => 'json'
                ],
                'callbackUrl' => [
                    'required' => false,
                    'type' => 'string',
                    'location' => 'json'
                ],
                'enabled' => [
                    'required' => false,
                    'type' => 'boolean',
                    'location' => 'json',
                ],
                'events' => [
                    'required' => false,
                    'type' => 'array',
                    'location' => 'json',
                ],
                'version' => [
                    'required' => false,
                    'type' => 'number',
                    'location' => 'json',
                ]
            ]
        ],

**Comment by Baggerone** [comment]
At first glance, it looks like you may be missing a closing bracket on your
`cells` entry.

Is that the problem?

**Comment by michiel75** [comment]
Sorry for the late response, but that does not solve it, keep getting teh same error message.
